name: Renovate

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Renovate
        uses: renovatebot/github-action@v41.0.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          LOG_LEVEL: "debug"
      - name: Test PR
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: |
            the first line is the commit message

            the commit description starts
            after a blank line and can be
            multiple lines
